### ISSUE TITLE
Update to 1.0.27

### ISSUE THREAD

**Issue by JayFoxRox** [lordmulder/libsndfile-MSVC#1]
Via http://www.mega-nerd.com/libsndfile/
- Version 1.0.26 (November 22 2015) Fix for CVE-2014-9496, CVE-2014-9756 and CVE-2015-7805. Add ALAC/CAF support. Minor bug fixes and improvements.
- Version 1.0.27 (June 19 2016) Fix a seek regression in 1.0.26. Add metadata read/write for CAF and RF64. FIx PAF endian-ness issue.

**Comment by lordmulder** [comment]
It's on my to-do list, though porting my changes to the new version will be quite some work :sweat_smile:

**Comment by JayFoxRox** [comment]
Any chance you could move it upstream?

---

We currently use libsndfile in our project (rwengine/OpenRW), but we think about dropping it due to not properly co-operating with MSVC (apparently) and not being on nuget or any other package managers for Windows.
We might even drop it as a dependency now (favoring SDL instead, which serves our needs too and is already a dependency).

We mostly care about properly supporting appveyor CI builds anyway.

**Comment by lordmulder** [comment]
The author of **libsndfile** has made clear that he has _no_ interest in maintaining MSVC support, because you can compile with MinGW on Windows. He won't even allow other people to maintain MSVC support, because he has been disappointed several time by people who just "disappeared". The _libsndfile_ DLL produced by MinGW works fine with MSVC applications. However, you need to compile the whole thing with MSVC compiler, if you need the **static** library. That's the reason for my fork to exist.

**Comment by JayFoxRox** [comment]
Okay, that just shows that the author is hard to co-operate with and I'll push for the transition.
A normal project has a good public repo - if MSVC breaks people would be able to fix it.
MinGW is not an option.

Make this low-priority then.
Also, feel free to delete the existing discussion if you want to keep your issues clean.

**Comment by lordmulder** [comment]
Sorry, it's been a while, but we are getting closer now:
[**libsndfile-MSVC.2017-01-17.zip**](https://github.com/lordmulder/libsndfile-MSVC/files/712475/libsndfile-MSVC.2017-01-17.zip)

I just updated *libsndfile* to v1.0.27. I also updated all *Xiph* audio libs (Ogg, Vorbis, FLAC) to latest.

Take it with a grain of salt, pretty much untested 😉

**Comment by lordmulder** [comment]
New version is released. Hope it's okay. Closing this ticket for now.
