### ISSUE TITLE
Adding DLL version

### ISSUE THREAD

**Issue by tomy2105** [lordmulder/libsndfile-MSVC#3]
I'm aware that MinGW/GCC can be used to build DLL version but that is not and ideal solution.

CMake of the upstream is still unusable/cumbersome for Windowsdevelopment (usage of autoheader, sed, grep).

Would you consider adding DLL building version to your project?

From my, hasty view it should be only matter of having another configuration with DLL type and LIBSNDFILE_DLL;LIBSNDFILE_DLL_EXPORT added in Preprocessor flags.

**Comment by lordmulder** [comment]
Well, it is **not** *that* simple, because *libsndfile* has some dependencies, such as *libflac*, *libogg* and *libvorbis*. Thus far, these have been compiled and provided as "static" libraries (`.lib`). 

So, one would have to decide whether we want an *"all-in-one"* `libsndfile` DLL that already has all the dependencies "built-in" as static libraries (I don't even know if that is possible, because I haven't tried), or whether we want to use a separate DLL file for each one of the required libraries 😐 

Anyhow, as soon as DLLs are involved, we can **not** compile with `/MT` switch ("static" C-Runtime) anymore, but have to revert to `/MD` compiler switch ("DLL" C-Runtime). And, since code compiled with `/MT` and `/MD` switch can **not** be mixed, we would have to re-compile all the dependencies, at the very least...

Regards.

**Comment by tomy2105** [comment]
Huh, yeah, I forgot about external libraries because I don't use this functionality for my projects :).
Yes. The /MD needs to be used, changed that when doing DLL build from your LIB one but forgot to mention in original post.
Anyway, external libraries definitely make things more complex, so let's close this for now.
